### PR TITLE
#637: primaryCodePath in modelInfo pointing to MeasureReport.type

### PR DESCRIPTION
**Pull request by echicoine-esac**

### CODE REVIEW

**Review by brynrhodes — APPROVED** [review]

**Review by brynrhodes — CHANGES_REQUESTED** [review]
Actually, wait, the primaryCodePath here should be just "type", not "MeasureReport.type", the MeasureReport qualifier is unnecessary.

**Comment by echicoine-esac** [comment]
> Actually, wait, the primaryCodePath here should be just "type", not "MeasureReport.type", the MeasureReport qualifier is unnecessary.

Updated entries to point to type

**Review by brynrhodes — APPROVED** [review]

**Review by JPercival — COMMENTED** [review]
Same question as #682. Are there tooling changes to support this generation?

**Comment by brynrhodes** [comment]
Agreed, added an issue: https://github.com/cqframework/cqf-tooling/issues/324

**Review by bryantaustin13 — APPROVED** [review]
LGTM

**Pull request merged**
