### PR TITLE
QuickFix: Upgrade commons-lang to commons-text to fix deprecation

### PR DESCRIPTION
**Pull request by vitorpamplona**
Classes below are deprecated and will soon be removed from `apache.commons.lang3`. 
- CharSequenceTranslator
- AggregateTranslator
- UnicodeUnescaper
- LookupTranslator
- JavaUnicodeEscaper

They were moved to `apache.commons.text`

### CODE REVIEW

**Review by JPercival — APPROVED** [review]

**Comment by JPercival** [comment]
Resolves #698

**Comment by JPercival** [comment]
@brynrhodes - This is a quick one. Can we get a review on it?

**Comment by JPercival** [comment]
Bryn's at DevDays. @mdnazmulkarim? Can I get a second review on this?

**Comment by JPercival** [comment]
@vitorpamplona - I see some conflicts. Can you resolve and I'll merge?

**Comment by vitorpamplona** [comment]
@JPercival ready to go here too.

**Pull request merged**
