### PR TITLE
Added libraryLine to all tests

### PR DESCRIPTION
**Pull request by ChrisMarkle**
I was using these files to test CQL Online. CQL Online requires a library line.

### CODE REVIEW

**Comment by cmoesel** [comment]
What is the purpose of adding the library line to all of the tests?  When the test data is built, one of the functions of the CoffeeScriptTestDataGenerator is to insert a library line automatically, if it is missing.  See:
https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/test/java/org/cqframework/cql/cql2elm/utilities/CoffeeScriptTestDataGenerator.java#L135-L137

**Comment by brynrhodes** [comment]
CQL doesn't require a library line, so I'd ask the same question as Chris, what's the purpose of adding the library line here?

**Comment by cmoesel** [comment]
Is it OK to close this PR? Unless there is a convincing argument to keep the library lines in, I don't think they're necessary.

**Comment by ChrisMarkle** [comment]
I agree. Close the PR.

Chris Markle
ESAC Inc Analyst
618.979.4421

**Pull request closed without merging**
