### PR TITLE
#95: Fixed annotations not including spans that reference ELM local i…

### PR DESCRIPTION
**Pull request by brynrhodes**
…dentifiers. The fix also addresses closed issues #86 and #61.

### CODE REVIEW

**Comment by cmoesel** [comment]
@brynrhodes -- It looks like Travis failed when attempting to compile the Java.  It can't find the `Chunk` class.  Is it possible you forgot to add a file to the commit -- or a new dependency in the build file?

**Comment by brynrhodes** [comment]
Sorry, missed that file. Committed now.

**Comment by alexanderelliott121** [comment]
I'm currently attempting to test this against CMS 177.
Currently seeing the following error when I try to run with annotations:



Error:[43:97, 43:111] Child chunk cannot be added because it is not contained within the parent chunk.
Error:[57:69, 57:90] elementType
Error:[59:23, 59:42] Could not validate reference to expression Initial Population because its definition contains errors.


I'm unable to attach the file I'm using for testing, I will email it to you separately.

**Comment by alexanderelliott121** [comment]
I can confirm that the ordering issue has been resolved.

**Pull request merged**
