### PR TITLE
#578 Support mapping expansion for arugments to a function

### PR DESCRIPTION
**Pull request by msargentibm**
Proposed change for https://github.com/cqframework/clinical_quality_language/issues/578.

I would also like to also add some tests if the code change seems ok. I would appreciate any suggestions folks might have as far as some of the test cases I should try to cover since I'm still getting used to the syntax used in a Model Info file.

### CODE REVIEW

**Review by brynrhodes — CHANGES_REQUESTED** [review]
Yes, the code change makes sense, a test case would be good to validate.

**Comment by msargentibm** [comment]
Thanks a lot! I'll work on adding some validation later today.

**Comment by msargentibm** [comment]
I took a shot at adding in a test case to the USCore BaseTest. I tried my best to follow the general structure of the cases before it. I tried including assertions for the key components from complex expression in the model info,  but was doubting whether I had too many or too few assertions for this particular case. Please let me know if you would like to see anything altered.

Thanks again for your review.

**Comment by msargentibm** [comment]
I wanted to follow up and see if there are changes I need to make in the validation case I added. Please let me know if there are any changes requested. Thanks!

**Comment by msargentibm** [comment]
Wanted to check in now that the holidays have passed. Are there further updates needed for this PR?

**Review by brynrhodes — APPROVED** [review]
Test looks great, thank you so much!

**Comment by brynrhodes** [comment]
So sorry for the delays here, the holidays really got the better of me :( Thank you so much for the contribution!

**Comment by msargentibm** [comment]
Not a problem! I know end of year is an extra busy time. Thanks for the change request and reviews!

**Pull request merged**
