### PR TITLE
#131: Changed retrieve to return profile types instead of base types …

### PR DESCRIPTION
**Pull request by brynrhodes**
…when used with profile types.

### CODE REVIEW

**Comment by brynrhodes** [comment]
Good point, I just committed updated XML and JSON ELM for all the spec examples.

**Comment by cmoesel** [comment]
Thanks.  That helps a lot.  I noticed there are now some translation errors due to QUICK, but I assume that's totally unrelated.

Seeing this in real life brings up a question for me though: is there still a use for the `templateId` field in retrieves?  Or does this make it irrelevant?

**Comment by brynrhodes** [comment]
I think it's still relevant because with something like FHIR, where a profile isn't necessarily defined as  a 'derived type'. It's also useful as a way to communicate the "label" of the type.

**Comment by cmoesel** [comment]
Maybe I'm not understanding, but is there even a path through the translator now that would result in the templateId being populated but _different_ than the class name?  I understand that for FHIR such a thing might make sense, but didn't this change just make it so that will never happen?

**Comment by brynrhodes** [comment]
Yes, the "templateId" element of the retrieve is set to the "identifier" of the type, which isn't necessarily the same as the name of the type. For FHIR-based models, we use that to identify the profile.

**Comment by cmoesel** [comment]
OK.  I think I was getting confused because the term _profile_ is used in multiple contexts here.

I'll accept the change.

**Comment by cmoesel** [comment]
Ah, shoot.  I just realized as I merged this that we should have run it by the Bonnie team -- or at least given them a heads up, as this might affect their patient source.  I was thinking they were already a part of the original conversation, but looking back at the issue (#131), I don't think they were.

@jbradl11 -- heads up!  Please let Bryn and me know if this is a big problem!

**Pull request merged**
