### PR TITLE
Add test for default timezone offset of DateTime

### PR DESCRIPTION
**Pull request by antvaset**
Closes https://github.com/cqframework/clinical_quality_language/issues/1420.

This PR adds tests for calling `DateTime(y, m, d, h, m, s, ms)` without specifying the timezone offset. As per the spec, it should default to the timezone offset of the evaluation request.

Note that when `engine.expression(...)` or `engine.evaluate(...)` is called without passing in the evaluation date time explicitly, it is set to `ZonedDateTime.now()`.

### CODE REVIEW

**Review by brynrhodes — CHANGES_REQUESTED** [review]
This is only the test, but doesn't the DateTimeEvaluator need to be updated as well?

**Comment by JPercival** [comment]
I walked through the code with Anton. The code looks correct to me. I think I was wrong before, the DateTimeEvaluator is using the timezone of the evaluation request.

**Comment by brynrhodes** [comment]
Hmm.... I walked through this the other day and it wasn't, just did again and I don't see how it is using the evaluation request timestamp:

https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/elm/executing/DateTimeEvaluator.java#L33

**Comment by JPercival** [comment]
The only place that's used is here:
https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/execution/EvaluationVisitor.java#L785-L786

Either the ELM has the offset embedded, or the current offset from the State object is used. That state is set up as part of the evaluation.

**Comment by brynrhodes** [comment]
I see, I was assuming the evaluator tree was still controlling the visit, but I see that it's the visitor now.

**Review by brynrhodes — APPROVED** [review]

**Review by JPercival — APPROVED** [review]

**Pull request merged**
